# XXX disable these & fix all the issues
rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }]
