# This file configures automatic labelling of pr's
# Adds the 'backend' label if any files change in the backend directory
backend: packages/backend/**/*
connector: packages/interledger/**/*
frontend: packages/frontend/**/*
repo: ./*