changelog:
  categories:
    - title: General Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Dependency Updates
      labels:
        - dependencies