env:
  browser: true
  es2021: true
  node: true
  jest: true
  amd: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }]
settings:
  react:
    version: "detect"