packageExtensions:
  "pino@*":
    dependencies:
      "pino-pretty": "*"
  "ilp-packet@*":
    dependencies:
      "@types/long": "4.0.1"
      "long": "^4.0.0"
  "@interledger/stream-receiver@*":
    dependencies:
      "ilp-protocol-ildcp": "^2.1.4"
  "@apollo/client@*":
    dependencies:
      "@types/react": "*"
      "react": "*"

yarnPath: '.yarn/releases/yarn-berry.cjs'
