packageExtensions:
  "pino@*":
    dependencies:
      "pino-pretty": "*"
  "ilp-packet@*":
    dependencies:
      "@types/long": "4.0.1"
      "long": "^4.0.0"

yarnPath: '.yarn/releases/yarn-berry.cjs'
