packageExtensions:
  "@apollo/client@*":
    dependencies:
      "@types/react": "*"
      react: "*"
  "@interledger/pay@*":
    dependencies:
      oer-utils: ^5.1.2
  "@interledger/stream-receiver@*":
    dependencies:
      ilp-protocol-ildcp: ^2.1.4
  ilp-packet@*:
    dependencies:
      "@types/long": 4.0.1
      long: ^4.0.0
  pino@*:
    dependencies:
      pino-pretty: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
enableInlineBuilds: true

nodeLinker: node-modules
