name: Publish Postman API version (tag)

on:
  push:
    tags:
      - '*'

jobs:
  postman-publish-main:
    uses: ./.github/workflows/postman/postman-publish.yaml
    with:
      api-version: ${{github.ref_name}}
      release-notes: "APIs corresponding to Rafiki version ${{github.ref_name}}"