apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tigerbeetle-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  fstype: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
