
name: 'rafiki'

services:
  cloud-nine-auth:
    hostname: cloud-nine-wallet-auth
    image: rafiki-auth
    build:
      context: ../..
      dockerfile: ./packages/auth/Dockerfile
    restart: always
    networks:
      - rafiki
    ports:
      - '3003:3003'
      - '3006:3006'
    environment:
      NODE_ENV: development
      AUTH_DATABASE_URL: postgresql://cloud_nine_wallet_auth:cloud_nine_wallet_auth@shared-database/cloud_nine_wallet_auth
    depends_on:
      - shared-database

  shared-database:
    image: 'postgres:15' # use latest official postgres version
    restart: unless-stopped
    networks:
      - rafiki
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ../cloud-nine-wallet/dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

volumes:
  database-data: # named volumes can be managed easier using docker-compose

networks:
  rafiki:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1
