version: '3'
services:
  mock-account-provider:
    hostname: happy-life-bank
    build:
      context: ../../..
      dockerfile: ./packages/mock-account-provider/Dockerfile
    restart: always
    networks:
      - rafiki
    ports:
      - '3031:80'
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      PORT: 80
      SEED_FILE_LOCATION: /workspace/seed.yml
      KEY_FILE: /workspace/private-key.pem
    volumes:
      - ./seed.yml:/workspace/seed.yml
      - ./private-key.pem:/workspace/private-key.pem
    depends_on:
      - backend
  backend:
    hostname: happy-life-bank-backend
    image: ghcr.io/interledger/rafiki-backend:latest
    build:
      context: ../../..
      dockerfile: ./packages/backend/Dockerfile
    restart: always
    privileged: true
    ports:
      - "4000:80"
      - "4001:3001"
    networks:
      - rafiki
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      ADMIN_PORT: 3001
      CONNECTOR_PORT: 3002
      OPEN_PAYMENTS_PORT: 80
      DATABASE_URL: postgresql://happy_life_bank_backend:happy_life_bank_backend@database/happy_life_bank_backend
      USE_TIGERBEETLE: ${USE_TIGERBEETLE-false}
      TIGERBEETLE_CLUSTER_ID: ${TIGERBEETLE_CLUSTER_ID-0}
      TIGERBEETLE_REPLICA_ADDRESSES: ${TIGERBEETLE_REPLICA_ADDRESSES-''}
      NONCE_REDIS_KEY: test
      AUTH_SERVER_GRANT_URL: http://happy-life-bank-auth:3006
      AUTH_SERVER_INTROSPECTION_URL: http://happy-life-bank-auth:3006/introspect
      ILP_ADDRESS: test.happy-life-bank
      STREAM_SECRET: BjPXtnd00G2mRQwP/8ZpwyZASOch5sUXT5o0iR5b5wU=
      ADMIN_KEY: admin
      PUBLIC_HOST: http://happy-life-bank-backend
      WEBHOOK_URL: http://happy-life-bank/webhooks
      OPEN_PAYMENTS_URL: http://happy-life-bank-backend
      PRICES_URL: http://happy-life-bank/prices
      REDIS_URL: redis://redis:6379/1
      QUOTE_URL: http://happy-life-bank/quotes
      PAYMENT_POINTER_URL: https://happy-life-bank-backend/.well-known/pay
  auth:
    hostname: happy-life-bank-auth
    image: ghcr.io/interledger/rafiki-auth:latest
    build:
      context: ../../..
      dockerfile: ./packages/auth/Dockerfile
    restart: always
    networks:
      - rafiki
    ports:
      - "4006:3006"
    environment:
      NODE_ENV: development
      AUTH_DATABASE_URL: postgresql://happy_life_bank_auth:happy_life_bank_auth@database/happy_life_bank_auth
      INTROSPECTION_HTTPSIG: "false"
      AUTH_SERVER_DOMAIN: "http://localhost:4006"
  signatures:
    hostname: happy-life-bank-signatures
    build:
      context: ../../..
      dockerfile: ./infrastructure/local/local-http-signatures/Dockerfile
    restart: always
    ports:
      - '3041:3000'
    environment:
      KEY_FILE: /workspace/private-key.pem
    volumes:
      - ./private-key.pem:/workspace/private-key.pem

networks:
  rafiki:
    external: true
