version: '3'
services:
  auth:
    build:
      context: ../..
      dockerfile: ./packages/auth/Dockerfile
  backend:
    build:
      context: ../..
      dockerfile: ./packages/backend/Dockerfile
  peer-auth:
    build:
      context: ../..
      dockerfile: ./packages/auth/Dockerfile
  peer-backend:
    build:
      context: ../..
      dockerfile: ./packages/backend/Dockerfile
