self:
  graphqlUrl: http://peer-backend:3001/graphql
  hostname: 'backend'
  mapHostname: 'primary-map'
peers:
  - asset: USD
    scale: 2
    initialLiquidity: 100000
    peerUrl: http://backend:3002
    peerIlpAddress: test.rafiki
accounts:
  - name: "Philip Fry"
    url: http://peer-backend/accounts/cbaker
    id: 742ab7cd-1624-4d2e-af6e-e15a71638669
    initialBalance: 1
    asset: USD
    scale: 2
  - name: "PlanEx Corp"
    id: 5726eefe-8737-459d-a36b-0acce152cb90
    initialBalance: 2000
    asset: USD
    scale: 2
    url: http://peer-backend/accounts/planex
