services:
  cloud-nine-backend:
    environment:
      ENABLE_TELEMETRY: true
      LIVENET: false
      OPEN_TELEMETRY_COLLECTOR_URLS: http://otel-collector:4317

  happy-life-backend:
    environment:
      ENABLE_TELEMETRY: true
      LIVENET: false
      OPEN_TELEMETRY_COLLECTOR_URLS: http://otel-collector:4317

  otel-collector:
    hostname: otel-collector
    image: otel/opentelemetry-collector:latest
    command: "--config=/etc/otel-collector-config.yaml"
    networks:
      - rafiki
    volumes:
      - ../telemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  prometheus:
    image: prom/prometheus:latest
    command: "--config.file=/etc/prometheus/prometheus.yaml --log.level=debug"
    networks:
      - rafiki
    volumes:
      - ../telemetry/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    networks:
    - rafiki
    ports:
     - '4500:3000'
    volumes:
     - grafana_storage:/var/lib/grafana
     - ../telemetry/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

volumes:
  grafana_storage:
