#Serves as example for the configuration of a local OpenTelemetry Collector
#Sigv4auth required for AWS Prometheus Remote Write access (USER with accesss keys needed)
extensions:
  sigv4auth:
    assume_role:
      arn: 'arn:aws:iam::145795521759:role/PrometheusRemoteWrite'
      sts_region: 'eu-west-2'

receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

processors:
  batch:

exporters:
  logging:
    verbosity: 'normal'
  prometheusremotewrite:
    endpoint: 'https://aps-workspaces.YOUR-REGION.amazonaws.com/workspaces/ws-YOUR-WORKSPACE-IDENTIFIER/api/v1/remote_write'
    auth:
      authenticator: sigv4auth

service:
  telemetry:
    logs:
      level: 'debug'
    metrics:
      level: 'detailed'
      address: 0.0.0.0:8888
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheusremotewrite]
