on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    types:
      - opened
      - synchronize

name: Release Docker Image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: build openapi
        run: yarn workspace openapi build

      - name: Build Docker Image
        run: yarn docker build backend -t ghcr.io/${{ github.repository_owner }}/rafiki-backend:${{ github.sha }} -t ghcr.io/${{ github.repository_owner }}/rafiki-backend:latest
        
      - name: Tag Docker Image with Tag Name
        if: github.ref_type == 'tag'
        run: docker tag ghcr.io/${{ github.repository_owner }}/rafiki-backend:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/rafiki-backend:${{ github.ref_name }}
