on:
  push:
    branches:
    - '*'
    tags:
    - '*'

name: Build / Release Docker Images

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - package: auth
            platforms: linux/amd64
          - package: backend
            platforms: linux/amd64,linux/arm64
          - package: frontend
            platforms: linux/amd64
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/rafiki-${{ matrix.package }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true #${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: packages/${{ matrix.package }}/Dockerfile
          platforms: ${{ matrix.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

