on:
  push:
    branches:
    - main

name: Release Docker Image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Build Docker Image
        run: yarn docker build backend -t ghcr.io/${{ github.actor }}/rafiki-backend:${{ github.sha }}

      - name: Login GHCR
        # You must create a personal access token on GitHub and add it to the 
        # repo's actions secrets named by 'GHCR_PAT' in order to use this step.
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/${{ github.actor }}/rafiki-backend:${{ github.sha }}