on:
  push:
    branches:
      - '!main'
  pull_request:
    types:
      - opened
      - synchronize

name: Integration Tests

# TODO: these show as seperate checks in PR... shouldn't 

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/workflows/rafiki/env-setup

      - name: Setup hosts
        run: |
          echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts

      - name: Build dependencies
        run: pnpm --filter integration build:deps

      - name: Run tests
        run: pnpm --filter integration run-tests