# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# This workflow uses the .github/labeler.yml to define the configuration.
# For more information, see:
# https://github.com/actions/labeler

name: "Pull Request Labeler"
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
