on:
  push:
    branches:
      - '!main'
  pull_request:
    types:
      - opened
      - synchronize

name: PR Checks

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm format:check
      - run: pnpm lint:check

  backend:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter openapi build
      - run: pnpm --filter auth build
      - run: pnpm --filter backend test

  frontend:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter frontend test

  auth:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter openapi build
      - run: pnpm --filter auth test

  openapi:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter openapi test

  build:
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend
      - auth
      - openapi
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm build

  all_pr_checks_passed:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - run: echo 'PR Checks Passed'
