on:
  push:
    branches:
      - '!main'
  pull_request:
    types:
      - opened
      - synchronize

name: PR Checks

jobs:
  checkout:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm checks

  graphql:
    runs-on: ubuntu-22.04
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/rafiki/env-setup

      - name: generate backend graphql
        run: pnpm --filter backend generate
      - name: generate auth graphql
        run: pnpm --filter auth generate

      - name: verify changed files
        uses: tj-actions/verify-changed-files@v19
        id: verify-changed-files
        with:
          files: |
            **/generated/graphql.*

      - name: fail if GraphQL was generated
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: exit 1

  backend:
    runs-on: ubuntu-22.04
    needs: [checkout]
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter backend build:deps
      - run: NODE_OPTIONS=--max-old-space-size=4096 pnpm --filter backend test:ci
      - name: AsyncAPI extension
        run: |
          echo "{\"extends\":[\"spectral:oas\",\"spectral:asyncapi\"]}" >> .spectral.json
      - name: Validate Open API specs
        run: |
          npx @stoplight/spectral-cli lint ./packages/backend/openapi/specs/webhooks.yaml

  frontend:
    runs-on: ubuntu-22.04
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter frontend typecheck
      - run: pnpm --filter frontend build

  auth:
    runs-on: ubuntu-22.04
    needs: [checkout]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter auth build:deps
      - run: pnpm --filter auth test
      - name: AsyncAPI extension
        run: |
          echo "{\"extends\":[\"spectral:oas\",\"spectral:asyncapi\"]}" >> .spectral.json
      - name: Validate Open API specs
        run: |
          npx @stoplight/spectral-cli lint ./packages/auth/openapi/specs/id-provider.yaml

  mock-account-servicing-entity:
    runs-on: ubuntu-22.04
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter mock-account-servicing-entity build
      - run: pnpm --filter mock-account-servicing-entity typecheck

  token-introspection:
    runs-on: ubuntu-22.04
    needs: checkout
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm --filter token-introspection test
      - name: AsyncAPI extension
        run: |
          echo "{\"extends\":[\"spectral:oas\",\"spectral:asyncapi\"]}" >> .spectral.json
      - name: Validate Open API specs
        run: |
          npx @stoplight/spectral-cli lint ./packages/token-introspection/openapi/specs/token-introspection.yaml

  integration-test:
    runs-on: ubuntu-22.04
    needs: checkout
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/workflows/rafiki/env-setup

      - name: Setup hosts
        run: |
          echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts

      - name: Build dependencies
        run: pnpm --filter integration build:deps

      - name: Run tests
        run: pnpm --filter integration run-tests

  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    needs:
      - backend
      - frontend
      - auth
      - mock-account-servicing-entity
      - token-introspection
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/rafiki/env-setup
      - run: pnpm build

  all_pr_checks_passed:
    runs-on: ubuntu-22.04
    needs:
      - build
      - integration-test
    steps:
      - run: echo 'PR Checks Passed'
