name: Trigger Rafiki Dev 

on:
  push:
    branches:
      - mk/test-trigger

jobs:
  trigger-rafiki-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Rafiki Dev Update
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'interledger',
              repo: 'rafiki.dev',
              workflow_id: 'workflows/generate-docs',
              ref: 'mk/test-trigger'
            });